### PR TITLE
Fix php constraint in composer.json

### PR DESCRIPTION
**Pull request by szepeviktor**
Composer still does it _better_ than others.

### CODE REVIEW

**Comment by szepeviktor** [comment]
🥦 https://youtu.be/j8Uz3IuYDh4?t=219 🥦

**Comment by szepeviktor** [comment]
@PrinsFrank

**Comment by PrinsFrank** [comment]
Sorry about that, this one got lost in my notifications. Thank you!!

**Comment by szepeviktor** [comment]
Very Glad to contribute.

**Pull request merged**
